# /srv/docker/linuxmuster-mail/docker-compose.yml
#
# thomas@linuxmuster.net
# 20181124

version: '2'

services:
  mail:
    image: tvial/docker-mailserver:release-v6.1.0
    hostname: @@mailhostname@@
    domainname: @@domainname@@
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - ./maildata/@@domainname@@/:/home/@@domainname@@/
    - ./mailstate/:/var/mail-state/
    - ./config/:/tmp/docker-mailserver/
    - ./config/ldap/ldap.conf:/etc/ldap/ldap.conf:ro
    - ./config/dovecot/dovecot-ldap.conf.ext:/etc/dovecot/dovecot-ldap.conf.ext:ro
    - ./config/postfix/ldap-users.cf:/etc/postfix/ldap-users.cf:ro
    - ./config/postfix/ldap-groups.cf:/etc/postfix/ldap-groups.cf:ro
    - ./config/postfix/ldap-aliases.cf:/etc/postfix/ldap-aliases.cf:ro
    - ./config/postfix/ldap-domains.cf:/etc/postfix/ldap-domains.cf:ro
    - ./config/saslauthd/saslauthd.conf:/etc/saslauthd.conf:ro
    - ./ssl:/etc/letsencrypt
    environment:
    - ENABLE_SPAMASSASSIN=0
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=0
    - ENABLE_POSTGREY=0
    - ONE_DIR=1
    - DMS_DEBUG=0
    - ENABLE_LDAP=1
    - LDAP_SERVER_HOST=ldaps://@@serverip@@:636
    - LDAP_SEARCH_BASE=@@basedn@@
    - LDAP_BIND_DN=uid=@@binduser@@,ou=accounts,@@basedn@@
    - LDAP_BIND_PW=@@binduserpw@@
    - DOVECOT_PASS_FILTER=(&(objectclass=person)(mail=%u))
    - DOVECOT_USER_FILTER=(&(objectclass=person)(mail=%u))
    - ENABLE_SASLAUTHD=1
    - SASLAUTHD_MECHANISMS=ldap
    - SASLAUTHD_LDAP_SERVER=ldaps://@@serverip@@:636
    - SASLAUTHD_LDAP_BIND_DN=uid=@@binduser@@,ou=accounts,@@basedn@@
    - SASLAUTHD_LDAP_PASSWORD=@@binduserpw@@
    - SASLAUTHD_LDAP_SEARCH_BASE=@@basedn@@
    - SASLAUTHD_LDAP_FILTER=uid=%u
    - POSTMASTER_ADDRESS=postmaster@@@domainname@@
    - SSL_TYPE=letsencrypt
    - AWS_SES_HOST=@@smtprelay@@
    - AWS_SES_USERPASS=@@smtpauth@@
    cap_add:
    - NET_ADMIN
